# path
save_dir: "./checkpoints/"
dataset_dir: "../SemanticKITTI/"
checkpoint_path:
pretrained_path: "./models/segformer/segformer.b1.1024x1024.city.160k.pth"


# training
batch_size: 8
learning_rate_init: 0.00001
weight_decay: 0.01
epoch: 100
warmup_epoch: 5
learning_rate_max: 0.001